/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.6.0-272
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v2';


// Services

export interface ClientPeerDef {
    hello: (message: string, callParams: CallParams<'message'>) => string | Promise<string>;
}
export function registerClientPeer(service: ClientPeerDef): void;
export function registerClientPeer(serviceId: string, service: ClientPeerDef): void;
export function registerClientPeer(peer: FluencePeer, service: ClientPeerDef): void;
export function registerClientPeer(peer: FluencePeer, serviceId: string, service: ClientPeerDef): void;
       

export function registerClientPeer(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "ClientPeer",
    "functions" : [
        {
            "functionName" : "hello",
            "argDefs" : [
                {
                    "name" : "message",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        }
    ]
}
    );
}
      


export interface MarketplaceServiceDef {
    opensea_fetch: (page: number, page_size: number, callParams: CallParams<'page' | 'page_size'>) => { msg: string; reply: string; } | Promise<{ msg: string; reply: string; }>;
    rarible_fetch: (continuation: string, size: number, callParams: CallParams<'continuation' | 'size'>) => { msg: string; reply: string; } | Promise<{ msg: string; reply: string; }>;
}
export function registerMarketplaceService(serviceId: string, service: MarketplaceServiceDef): void;
export function registerMarketplaceService(peer: FluencePeer, serviceId: string, service: MarketplaceServiceDef): void;
       

export function registerMarketplaceService(...args: any) {
    registerService(
        args,
        {
    "functions" : [
        {
            "functionName" : "opensea_fetch",
            "argDefs" : [
                {
                    "name" : "page",
                    "argType" : {
                        "tag" : "primitive"
                    }
                },
                {
                    "name" : "page_size",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "rarible_fetch",
            "argDefs" : [
                {
                    "name" : "continuation",
                    "argType" : {
                        "tag" : "primitive"
                    }
                },
                {
                    "name" : "size",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        }
    ]
}
    );
}
      
// Functions
 

export function fetchRarible(
    targetPeerId: string,
    targetRelayPeerId: string,
    continuation: string,
    size: number,
    config?: {ttl?: number}
): Promise<string>;

export function fetchRarible(
    peer: FluencePeer,
    targetPeerId: string,
    targetRelayPeerId: string,
    continuation: string,
    size: number,
    config?: {ttl?: number}
): Promise<string>;

export function fetchRarible(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (seq
                             (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                             (call %init_peer_id% ("getDataSrv" "targetPeerId") [] targetPeerId)
                            )
                            (call %init_peer_id% ("getDataSrv" "targetRelayPeerId") [] targetRelayPeerId)
                           )
                           (call %init_peer_id% ("getDataSrv" "continuation") [] continuation)
                          )
                          (call %init_peer_id% ("getDataSrv" "size") [] size)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (xor
                         (seq
                          (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("4423f13c-ea6c-4012-894d-8bed346bdf40" "rarible_fetch") [continuation size] comp)
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (seq
                          (seq
                           (seq
                            (call -relay- ("op" "noop") [])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                           )
                           (call -relay- ("op" "noop") [])
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                        )
                       )
                       (xor
                        (seq
                         (seq
                          (par
                           (call targetPeerId ("ClientPeer" "hello") [%init_peer_id%])
                           (null)
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (seq
                          (call targetRelayPeerId ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [comp.$.reply!])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "fetchRarible",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "targetPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "targetRelayPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "continuation",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "size",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 

export function fetchOpenSea(
    targetPeerId: string,
    targetRelayPeerId: string,
    page: number,
    page_size: number,
    config?: {ttl?: number}
): Promise<string>;

export function fetchOpenSea(
    peer: FluencePeer,
    targetPeerId: string,
    targetRelayPeerId: string,
    page: number,
    page_size: number,
    config?: {ttl?: number}
): Promise<string>;

export function fetchOpenSea(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (seq
                             (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                             (call %init_peer_id% ("getDataSrv" "targetPeerId") [] targetPeerId)
                            )
                            (call %init_peer_id% ("getDataSrv" "targetRelayPeerId") [] targetRelayPeerId)
                           )
                           (call %init_peer_id% ("getDataSrv" "page") [] page)
                          )
                          (call %init_peer_id% ("getDataSrv" "page_size") [] page_size)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (xor
                         (seq
                          (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("4423f13c-ea6c-4012-894d-8bed346bdf40" "opensea_fetch") [page page_size] comp)
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (seq
                          (seq
                           (seq
                            (call -relay- ("op" "noop") [])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                           )
                           (call -relay- ("op" "noop") [])
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                        )
                       )
                       (xor
                        (seq
                         (seq
                          (par
                           (call targetPeerId ("ClientPeer" "hello") [%init_peer_id%])
                           (null)
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (seq
                          (call targetRelayPeerId ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [comp.$.reply!])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "fetchOpenSea",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "targetPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "targetRelayPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "page",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "page_size",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}
