/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.6.0-272
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v2';


// Services

export interface ClientPeerDef {
    hello: (message: string, callParams: CallParams<'message'>) => string | Promise<string>;
}
export function registerClientPeer(service: ClientPeerDef): void;
export function registerClientPeer(serviceId: string, service: ClientPeerDef): void;
export function registerClientPeer(peer: FluencePeer, service: ClientPeerDef): void;
export function registerClientPeer(peer: FluencePeer, serviceId: string, service: ClientPeerDef): void;
       

export function registerClientPeer(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "ClientPeer",
    "functions" : [
        {
            "functionName" : "hello",
            "argDefs" : [
                {
                    "name" : "message",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        }
    ]
}
    );
}
      


export interface MarketplaceServiceDef {
    hello: (from: string, callParams: CallParams<'from'>) => { msg: string; reply: string; } | Promise<{ msg: string; reply: string; }>;
    opensea_fetch: (callParams: CallParams<null>) => { msg: string; reply: string; } | Promise<{ msg: string; reply: string; }>;
    opensea_fetch_len: (callParams: CallParams<null>) => { msg: string; reply: string; } | Promise<{ msg: string; reply: string; }>;
    rarible_fetch: (callParams: CallParams<null>) => { msg: string; reply: string; } | Promise<{ msg: string; reply: string; }>;
    rarible_fetch_len: (callParams: CallParams<null>) => { msg: string; reply: string; } | Promise<{ msg: string; reply: string; }>;
}
export function registerMarketplaceService(serviceId: string, service: MarketplaceServiceDef): void;
export function registerMarketplaceService(peer: FluencePeer, serviceId: string, service: MarketplaceServiceDef): void;
       

export function registerMarketplaceService(...args: any) {
    registerService(
        args,
        {
    "functions" : [
        {
            "functionName" : "hello",
            "argDefs" : [
                {
                    "name" : "from",
                    "argType" : {
                        "tag" : "primitive"
                    }
                }
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "opensea_fetch",
            "argDefs" : [
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "opensea_fetch_len",
            "argDefs" : [
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "rarible_fetch",
            "argDefs" : [
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        },
        {
            "functionName" : "rarible_fetch_len",
            "argDefs" : [
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        }
    ]
}
    );
}
      
// Functions
 

export function fetchOpenSea(
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function fetchOpenSea(
    peer: FluencePeer,
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function fetchOpenSea(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                           (call %init_peer_id% ("getDataSrv" "targetPeerId") [] targetPeerId)
                          )
                          (call %init_peer_id% ("getDataSrv" "targetRelayPeerId") [] targetRelayPeerId)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (xor
                         (seq
                          (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("7f792f0b-8e9b-4b6d-90f7-bd6461e84d1d" "opensea_fetch") [] comp)
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (seq
                          (seq
                           (seq
                            (call -relay- ("op" "noop") [])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                           )
                           (call -relay- ("op" "noop") [])
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                        )
                       )
                       (xor
                        (seq
                         (seq
                          (par
                           (call targetPeerId ("ClientPeer" "hello") [%init_peer_id%])
                           (null)
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (seq
                          (call targetRelayPeerId ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [comp.$.reply!])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "fetchOpenSea",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "targetPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "targetRelayPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 

export function sayHello(
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function sayHello(
    peer: FluencePeer,
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function sayHello(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                           (call %init_peer_id% ("getDataSrv" "targetPeerId") [] targetPeerId)
                          )
                          (call %init_peer_id% ("getDataSrv" "targetRelayPeerId") [] targetRelayPeerId)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (xor
                         (seq
                          (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("7f792f0b-8e9b-4b6d-90f7-bd6461e84d1d" "hello") ["With love"] comp)
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (seq
                          (seq
                           (seq
                            (call -relay- ("op" "noop") [])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                           )
                           (call -relay- ("op" "noop") [])
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                        )
                       )
                       (xor
                        (seq
                         (seq
                          (par
                           (call targetPeerId ("ClientPeer" "hello") [%init_peer_id%])
                           (null)
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (seq
                          (call targetRelayPeerId ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [comp.$.reply!])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "sayHello",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "targetPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "targetRelayPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 

export function fetchRarible(
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function fetchRarible(
    peer: FluencePeer,
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function fetchRarible(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                           (call %init_peer_id% ("getDataSrv" "targetPeerId") [] targetPeerId)
                          )
                          (call %init_peer_id% ("getDataSrv" "targetRelayPeerId") [] targetRelayPeerId)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (xor
                         (seq
                          (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("7f792f0b-8e9b-4b6d-90f7-bd6461e84d1d" "rarible_fetch") [] comp)
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (seq
                          (seq
                           (seq
                            (call -relay- ("op" "noop") [])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                           )
                           (call -relay- ("op" "noop") [])
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                        )
                       )
                       (xor
                        (seq
                         (seq
                          (par
                           (call targetPeerId ("ClientPeer" "hello") [%init_peer_id%])
                           (null)
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (seq
                          (call targetRelayPeerId ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [comp.$.reply!])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "fetchRarible",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "targetPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "targetRelayPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 

export function fetchRaribleSize(
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function fetchRaribleSize(
    peer: FluencePeer,
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function fetchRaribleSize(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                           (call %init_peer_id% ("getDataSrv" "targetPeerId") [] targetPeerId)
                          )
                          (call %init_peer_id% ("getDataSrv" "targetRelayPeerId") [] targetRelayPeerId)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (xor
                         (seq
                          (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("7f792f0b-8e9b-4b6d-90f7-bd6461e84d1d" "rarible_fetch_len") [] comp)
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (seq
                          (seq
                           (seq
                            (call -relay- ("op" "noop") [])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                           )
                           (call -relay- ("op" "noop") [])
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                        )
                       )
                       (xor
                        (seq
                         (seq
                          (par
                           (call targetPeerId ("ClientPeer" "hello") [%init_peer_id%])
                           (null)
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (seq
                          (call targetRelayPeerId ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [comp.$.reply!])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "fetchRaribleSize",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "targetPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "targetRelayPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

 

export function fetchOpenSeaSize(
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function fetchOpenSeaSize(
    peer: FluencePeer,
    targetPeerId: string,
    targetRelayPeerId: string,
    config?: {ttl?: number}
): Promise<string>;

export function fetchOpenSeaSize(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                           (call %init_peer_id% ("getDataSrv" "targetPeerId") [] targetPeerId)
                          )
                          (call %init_peer_id% ("getDataSrv" "targetRelayPeerId") [] targetRelayPeerId)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (xor
                         (seq
                          (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("7f792f0b-8e9b-4b6d-90f7-bd6461e84d1d" "opensea_fetch_len") [] comp)
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (seq
                          (seq
                           (seq
                            (call -relay- ("op" "noop") [])
                            (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                           )
                           (call -relay- ("op" "noop") [])
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                        )
                       )
                       (xor
                        (seq
                         (seq
                          (par
                           (call targetPeerId ("ClientPeer" "hello") [%init_peer_id%])
                           (null)
                          )
                          (call targetRelayPeerId ("op" "noop") [])
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (seq
                          (call targetRelayPeerId ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [comp.$.reply!])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "fetchOpenSeaSize",
    "returnType" : {
        "tag" : "primitive"
    },
    "argDefs" : [
        {
            "name" : "targetPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        },
        {
            "name" : "targetRelayPeerId",
            "argType" : {
                "tag" : "primitive"
            }
        }
    ],
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}
